### ISSUE TITLE
Headers in codeblocks should be ignored

### ISSUE THREAD

**Issue by Hoffenbar** [h3rald/hastyscribe#75] opened 2021-01-27 11:05 UTC
I noticed that # within Codeblocks (within 3 backticks) are taken into account for the table of content.
Additionally, they are rendered within the codeblock.

**Comment by h3rald** [comment] 2021-01-27 17:59
Uhm... nasty. This could be a bug in the discount markdown library.

Did you try escaping the #s with a backslash? That normally does the trick. Not ideal, but a workaround at least!

**Comment by Hoffenbar** [comment] 2021-01-27 20:20
I haven't tried escaping yet. I must admin that the document is kind of strange. I have a rather large codeblock there with hundrets of short lines, many of them begin with a hash.
I also noticed this message twice when processing the .md: `(!) Snippet 'catalogReturnLink' not defined.`
Unfortunally, I could not give you the source because it contains secret internals of our company.
So I just tried to assemble a simple document which triggers the behaviour.
For this I created that:

    # Test

    ## Test

    ```
    # comment
    # another comment
    a string with backslashes d:\folder\file.ext
    ; somthing *else*
    # everything within a code block should be printed out as is?
    ```

But with this, I get this error:
`fatal.nim(49)            sysFatal`
`Error: unhandled exception: index out of bounds, the container is empty [IndexDefect]`

**Comment by h3rald** [comment] 2021-01-27 20:37
OK this is weird, I just ran the snippet you posted through HastyScribe and didn't get any error, furthermore the conversion looks alright, and `#`s within the code block are ignored:

```
<h1>Test</h1>  
                                  
<h2>Test</h2>

<pre><code># comment
# another comment
a string with backslashes d:\folder\file.ext
; somthing *else*
 # everything within a code block should be         printed out as is?
 </code></pre>
```

There must be something else in your document that causes that behavior.

The other error about the snippet not being found should be due to a string like `{{catalogReturnLink}}` somewhere in your document. That basically is a reference to a text snippet (which is however not defined anywhere) according to HastyScribe syntax.

**Comment by Hoffenbar** [comment] 2021-01-27 20:49
Hello, thank you. Yes, I tried the last example again by myself, and it worked. I think I should better hit save in the editor before trying something like this. Ok, I'll try to derive a document from the real one to narrow down the cause - tomorrow.

**Comment by Hoffenbar** [comment] 2021-01-27 23:10
Just tested the suspicious codeblock alone, and it just works well.
So the reason for the "hickup" is some other fact.
I'll investigate further....

**Comment by Hoffenbar** [comment] 2021-01-27 23:17
While testing, the following failed:

    ```
        <location path="Default Web Site">
            <system.webServer>
                <handlers accessPolicy="Read, Execute, Script">
                    <add name="Tclsh" path="*.tsh" verb="*" modules="CgiModule" scriptProcessor="D:\htdocs\cgi-bin\cgitcl.exe "%s"" resourceType="File" requireAccess="Execute" />
                </handlers>
                <security>
                    <authentication>
                        <windowsAuthentication enabled="true" />
                        <anonymousAuthentication enabled="false" />
                    </authentication>
                </security>
            </system.webServer>
        </location>
        <location path="Default Web Site/cgi-bin">
            <system.webServer>
                <handlers>
                    <add name="ZoomSearch" path="*.cgi" verb="*" modules="CgiModule" resourceType="File" requireAccess="Execute" />
                </handlers>
            </system.webServer>
        </location>

    </configuration>
    ```
The resulting webpage looks like this:
    ``` <system.webServer> </system.webServer> <system.webServer> </system.webServer>

    ``
It should't matter what´s inside the backticks?

**Comment by Hoffenbar** [comment] 2021-01-27 23:24
I think I got it!
I'm very sorry. I had a construct somewhere like this:

    ...... [...comment....].......

I think the square brackets are interpreted as part of a link structure like this:

    [name](url)

After I changed the text to 

    .... {...comment...}......

everything works fine!

**Comment by Hoffenbar** [comment] 2021-01-28 13:33
Just tried another example, but it works perfectly well:

    # Test

    ```
    # Test11
    Other
    ## Test12
    ```

    Wrong link: [Something in square brackets] not directly followed by (round brackets)

    ```
    # Test21
    Other
    ## Test22
    ```
It seems to me that the reason for the error was a unknown combination of things which I couldn't easily put into an easy example for testing yet.

**Comment by h3rald** [comment] 2021-01-28 20:17
Weird...

OR, something like this could well happen even if you forget a single "`"

Closing this for now, please reopen if you can reproduce the problem!

**Closed** 2021-01-28 20:17 UTC

**Comment by Hoffenbar** [comment] 2021-01-28 20:20
ok!
