### ISSUE TITLE
Accentued caracters

### ISSUE THREAD

**Issue by zemadmat** [h3rald/hastyscribe#50] opened 2017-01-09 10:35 UTC
Hi,
How can i have a valid output with accentued caracters ?
For the moment when i convert a such caracter i have a question mark.

intégration -> int�gration
Cheers

**Comment by h3rald** [comment] 2017-01-10 10:34
Hi, 

I did some simple tests and in my case accented characters like àèìòù seem to work fine, when I just input them with the keyboard.

For sure at worst you could encode them as HTML entitites, e.g. &agrave; &egrave; &igrave; etc.: (see [this](http://www.w3schools.com/charsets/ref_html_entities_a.asp) for more info)... but could you please attach the markdown file you are trying to convert, so I can test it and see?

**Comment by zemadmat** [comment] 2017-01-11 13:57
Hi please find attached the incriminated file :)
Cheers 

    Le Mardi 10 janvier 2017 11h34, Fabio Cevasco <notifications@github.com> a écrit :
 
 

 Hi,I did some simple tests and in my case accented characters like àèìòù seem to work fine, when I just input them with the keyboard.For sure at worst you could encode them as HTML entitites, e.g. à è ì etc.: (see this for more info)... but could you please attach the markdown file you are trying to convert, so I can test it and see?—

**Comment by h3rald** [comment] 2017-01-15 13:03
Mmmm can't find any file... could you attach it to the github issue or send it by email to h3rald@h3rald.com.

Thanks!

**Comment by h3rald** [comment] 2017-02-18 14:32
Cannot reproduce; closing this issue.

**Closed by h3rald** 2017-02-18 14:32 UTC
